import { saveCompanies, CompanyConfig } from '../lib/storage';

const EXPANDED_SOURCES: CompanyConfig[] = [
  {
    id: 'comp-stripe',
    name: 'Stripe',
    ats: 'greenhouse',
    slug: 'stripe',
    careersUrl: 'https://stripe.com/jobs',
    priority: 1,
    isActive: true,
  },
  {
    id: 'comp-anthropic',
    name: 'Anthropic',
    ats: 'lever',
    slug: 'anthropic',
    careersUrl: 'https://anthropic.com/careers',
    priority: 1,
    isActive: true,
  },
  {
    id: 'comp-linear',
    name: 'Linear',
    ats: 'ashby',
    slug: 'linear',
    careersUrl: 'https://linear.app/careers',
    priority: 1,
    isActive: true,
  },
  {
    id: 'comp-ramp',
    name: 'Ramp',
    ats: 'ashby',
    slug: 'ramp',
    careersUrl: 'https://ramp.com/careers',
    priority: 1,
    isActive: true,
  },
  {
    id: 'comp-datadog',
    name: 'Datadog',
    ats: 'greenhouse',
    slug: 'datadog',
    careersUrl: 'https://www.datadoghq.com/careers',
    priority: 1,
    isActive: true,
  },
  {
    id: 'comp-figma',
    name: 'Figma',
    ats: 'lever',
    slug: 'figma',
    careersUrl: 'https://www.figma.com/careers',
    priority: 1,
    isActive: true,
  },
  {
    id: 'comp-vercel',
    name: 'Vercel',
    ats: 'greenhouse',
    slug: 'vercel',
    careersUrl: 'https://vercel.com/careers',
    priority: 1,
    isActive: true,
  },
  {
    id: 'comp-openai',
    name: 'OpenAI',
    ats: 'greenhouse',
    slug: 'openai',
    careersUrl: 'https://openai.com/careers',
    priority: 1,
    isActive: true,
  },
  {
    id: 'comp-airbnb',
    name: 'Airbnb',
    ats: 'greenhouse',
    slug: 'airbnb',
    careersUrl: 'https://careers.airbnb.com',
    priority: 2,
    isActive: true,
  },
  {
    id: 'comp-akamai',
    name: 'Akamai',
    ats: 'greenhouse',
    slug: 'akamai',
    careersUrl: 'https://www.akamai.com/careers',
    priority: 2,
    isActive: true,
  },
  {
    id: 'comp-automattic',
    name: 'Automattic',
    ats: 'greenhouse',
    slug: 'automatticcareers',
    careersUrl: 'https://automattic.com/work-with-us',
    priority: 1,
    isActive: true,
  },
  {
    id: 'comp-doximity',
    name: 'Doximity',
    ats: 'greenhouse',
    slug: 'doximity',
    careersUrl: 'https://workat.doximity.com',
    priority: 2,
    isActive: true,
  },
  {
    id: 'comp-gitlab',
    name: 'GitLab',
    ats: 'greenhouse',
    slug: 'gitlab',
    careersUrl: 'https://about.gitlab.com/jobs',
    priority: 1,
    isActive: true,
  },
  {
    id: 'comp-postman',
    name: 'Postman',
    ats: 'ashby',
    slug: 'postman',
    careersUrl: 'https://www.postman.com/careers',
    priority: 1,
    isActive: true,
  },
  {
    id: 'comp-supabase',
    name: 'Supabase',
    ats: 'ashby',
    slug: 'supabase',
    careersUrl: 'https://supabase.com/careers',
    priority: 1,
    isActive: true,
  },
  {
    id: 'comp-elastic',
    name: 'Elastic',
    ats: 'greenhouse',
    slug: 'elastic',
    careersUrl: 'https://www.elastic.co/about/careers',
    priority: 1,
    isActive: true,
  },
  {
    id: 'comp-canonical',
    name: 'Canonical',
    ats: 'greenhouse',
    slug: 'canonical',
    careersUrl: 'https://canonical.com/careers',
    priority: 1,
    isActive: true,
  },
  {
    id: 'comp-docker',
    name: 'Docker',
    ats: 'greenhouse',
    slug: 'docker',
    careersUrl: 'https://www.docker.com/careers',
    priority: 1,
    isActive: true,
  },
  {
    id: 'comp-grafanalabs',
    name: 'Grafana Labs',
    ats: 'greenhouse',
    slug: 'grafanalabs',
    careersUrl: 'https://grafana.com/about/careers',
    priority: 1,
    isActive: true,
  },
  {
    id: 'comp-hashicorp',
    name: 'HashiCorp',
    ats: 'greenhouse',
    slug: 'hashicorp',
    careersUrl: 'https://www.hashicorp.com/careers',
    priority: 1,
    isActive: true,
  },
  {
    id: 'comp-mozilla',
    name: 'Mozilla',
    ats: 'greenhouse',
    slug: 'mozilla',
    careersUrl: 'https://www.mozilla.org/en-US/careers',
    priority: 1,
    isActive: true,
  },
  {
    id: 'comp-mongodb',
    name: 'MongoDB',
    ats: 'greenhouse',
    slug: 'mongodb',
    careersUrl: 'https://www.mongodb.com/careers',
    priority: 1,
    isActive: true,
  },
  {
    id: 'comp-cloudflare',
    name: 'Cloudflare',
    ats: 'greenhouse',
    slug: 'cloudflare',
    careersUrl: 'https://www.cloudflare.com/careers',
    priority: 1,
    isActive: true,
  },
  {
    id: 'comp-sourcegraph',
    name: 'Sourcegraph',
    ats: 'greenhouse',
    slug: 'sourcegraph',
    careersUrl: 'https://sourcegraph.com/jobs',
    priority: 1,
    isActive: true,
  },
  {
    id: 'comp-snyk',
    name: 'Snyk',
    ats: 'greenhouse',
    slug: 'snyk',
    careersUrl: 'https://snyk.io/careers',
    priority: 1,
    isActive: true,
  },
  {
    id: 'comp-github',
    name: 'GitHub',
    ats: 'greenhouse',
    slug: 'github',
    careersUrl: 'https://github.com/about/careers',
    priority: 1,
    isActive: true,
  },
  {
    id: 'comp-databricks',
    name: 'Databricks',
    ats: 'greenhouse',
    slug: 'databricks',
    careersUrl: 'https://www.databricks.com/company/careers',
    priority: 1,
    isActive: true,
  },
  {
    id: 'comp-resend',
    name: 'Resend',
    ats: 'workable',
    slug: 'resend',
    careersUrl: 'https://resend.com/careers',
    priority: 1,
    isActive: true,
  },
  {
    id: 'comp-monzo',
    name: 'Monzo',
    ats: 'recruitee',
    slug: 'monzo',
    careersUrl: 'https://monzo.com/careers',
    priority: 1,
    isActive: true,
  },
  {
    id: 'comp-hn',
    name: 'Hacker News (Who is Hiring)',
    ats: 'hn',
    slug: 'whoishiring',
    careersUrl: 'https://news.ycombinator.com',
    priority: 1,
    isActive: true,
  },
  {
    id: 'comp-tokyodev',
    name: 'TokyoDev (Japan Tech)',
    ats: 'tokyodev',
    slug: 'tokyodev',
    careersUrl: 'https://www.tokyodev.com/jobs',
    priority: 1,
    isActive: true,
  },
  {
    id: 'comp-japandev',
    name: 'Japan Dev (Japan Tech)',
    ats: 'japandev',
    slug: 'japandev',
    careersUrl: 'https://japan-dev.com',
    priority: 1,
    isActive: true,
  },
  {
    id: 'comp-wwr-backend',
    name: 'We Work Remotely (Backend RSS)',
    ats: 'rss',
    slug: 'https://weworkremotely.com/categories/remote-back-end-programming-jobs.rss',
    careersUrl: 'https://weworkremotely.com',
    priority: 1,
    isActive: true,
  },
  {
    id: 'comp-wwr-fullstack',
    name: 'We Work Remotely (Full-Stack RSS)',
    ats: 'rss',
    slug: 'https://weworkremotely.com/categories/remote-full-stack-programming-jobs.rss',
    careersUrl: 'https://weworkremotely.com',
    priority: 1,
    isActive: true,
  },
];

console.log(`Seeding ${EXPANDED_SOURCES.length} sources to storage...`);
saveCompanies(EXPANDED_SOURCES);
console.log(`Successfully synced ${EXPANDED_SOURCES.length} active sources to SQLite and JSON!`);
